variables:
  - &install_pnpm "npm i -g corepack && corepack enable pnpm"

steps:
  prettier_check:
    image: jauderho/prettier:3.9.4-alpine
    commands:
      - prettier --no-config --arrow-parens avoid -c .
    when:
      - event: pull_request

  install:
    image: node:24-alpine
    commands:
      - *install_pnpm
      - pnpm i
    when:
      - event: pull_request

  lint:
    image: node:24-alpine
    commands:
      - *install_pnpm
      - pnpm lint
    when:
      - event: pull_request

  notify_success:
    image: codeberg.org/l-x/woodpecker-ntfy
    when:
      - event: pull_request
        status: [success]
    settings:
      url: https://ntfy.sh/lemmy_drone_ci
      title: "✔️ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}"
      message: ${CI_PIPELINE_URL}
      click: ${CI_PIPELINE_URL}

  notify_failure:
    image: codeberg.org/l-x/woodpecker-ntfy
    when:
      - event: pull_request
        status: [failure]
    settings:
      url: https://ntfy.sh/lemmy_drone_ci
      title: "❌ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}"
      message: ${CI_PIPELINE_URL}
      click: ${CI_PIPELINE_URL}
